#!/bin/bash
var="start restart stop reload status enable disable"
if ! [ -z $1 ]
    then
        if ! [ -z $2 ]
            then
            if [[ ! "$2" =~ ["^$var"] ]]; 
                then
                    systemctl $2 $1
            fi
            else
                echo "WTF !@_@?"
        fi
    else
        echo "WTF !@_@?"
fi
